/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.rytways.nsn.db.example;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import com.rytways.nsn.db.dao.LogindetailsviewDao;
import com.rytways.nsn.db.dto.Logindetailsview;
import com.rytways.nsn.db.exceptions.LogindetailsviewDaoException;
import com.rytways.nsn.db.factory.LogindetailsviewDaoFactory;

public class LogindetailsviewDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		// findAll();
		// findWhereEmpPhotoEquals("");
		// findWhereLoginIdEquals(0);
		// findWhereEmpCodeEquals(0);
		// findWhereEmpIdEquals(0);
		// findWhereEmpNameEquals("");
		// findWhereCertifiedStatusEquals(0);
		// findWhereStageNameEquals("");
		// findWhereProductFamilyNameEquals("");
		// findWhereLineIdEquals(0);
		// findWhereUpdatedDateTimeEquals(null);
		// findWhereStatusEquals(0);
		// findWhereStageidEquals(0);
		// findWhereProductFamilyIdEquals(0);
		// findWhereShiftEquals(0);
		// findWhereIpaddressEquals("");
		// findWhereLoginDateEquals(null);
		// findWhereLineNameEquals("");
		// findWhereLineStatusEquals(0);
		// findWhereLineOrderNoEquals(0);
		// findWhereProductFamilyStatusEquals(0);
		// findWhereGenderEquals("");
		// findWhereFunctionIdEquals(0);
		// findWhereAttendanceDateEquals("");
		// findWhereTuningStationNoEquals("");
		// findWhereRouteNameEquals("");
		// findWhereFunctionNameEquals("");
		// findWhereLogoutDateEquals(null);
		// findWhereShiftDateEquals(null);
		// findWhereTuningStatusEquals(0);
		// findWhereTuningAverageTimeEquals(0);
		// findWhereNoOfUnitsTunedEquals(0);
		// findWhereBatchEquals(0);
		// findWhereEmpStatusEquals(0);
		// findWhereBatchNameEquals("");
		// findWhereErtmemberEquals(0);
		// findWhereNoOfCertiEquals(0);
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			LogindetailsviewDao _dao = getLogindetailsviewDao();
			Logindetailsview _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereEmpPhotoEquals'
	 * 
	 * @param empPhoto
	 */
	public static void findWhereEmpPhotoEquals(String empPhoto)
	{
		try {
			LogindetailsviewDao _dao = getLogindetailsviewDao();
			Logindetailsview _result[] = _dao.findWhereEmpPhotoEquals(empPhoto);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereLoginIdEquals'
	 * 
	 * @param loginId
	 */
	public static void findWhereLoginIdEquals(int loginId)
	{
		try {
			LogindetailsviewDao _dao = getLogindetailsviewDao();
			Logindetailsview _result[] = _dao.findWhereLoginIdEquals(loginId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereEmpCodeEquals'
	 * 
	 * @param empCode
	 */
	public static void findWhereEmpCodeEquals(int empCode)
	{
		try {
			LogindetailsviewDao _dao = getLogindetailsviewDao();
			Logindetailsview _result[] = _dao.findWhereEmpCodeEquals(empCode);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereEmpIdEquals'
	 * 
	 * @param empId
	 */
	public static void findWhereEmpIdEquals(int empId)
	{
		try {
			LogindetailsviewDao _dao = getLogindetailsviewDao();
			Logindetailsview _result[] = _dao.findWhereEmpIdEquals(empId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereEmpNameEquals'
	 * 
	 * @param empName
	 */
	public static void findWhereEmpNameEquals(String empName)
	{
		try {
			LogindetailsviewDao _dao = getLogindetailsviewDao();
			Logindetailsview _result[] = _dao.findWhereEmpNameEquals(empName);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereCertifiedStatusEquals'
	 * 
	 * @param certifiedStatus
	 */
	public static void findWhereCertifiedStatusEquals(int certifiedStatus)
	{
		try {
			LogindetailsviewDao _dao = getLogindetailsviewDao();
			Logindetailsview _result[] = _dao.findWhereCertifiedStatusEquals(certifiedStatus);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereStageNameEquals'
	 * 
	 * @param stageName
	 */
	public static void findWhereStageNameEquals(String stageName)
	{
		try {
			LogindetailsviewDao _dao = getLogindetailsviewDao();
			Logindetailsview _result[] = _dao.findWhereStageNameEquals(stageName);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereProductFamilyNameEquals'
	 * 
	 * @param productFamilyName
	 */
	public static void findWhereProductFamilyNameEquals(String productFamilyName)
	{
		try {
			LogindetailsviewDao _dao = getLogindetailsviewDao();
			Logindetailsview _result[] = _dao.findWhereProductFamilyNameEquals(productFamilyName);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereLineIdEquals'
	 * 
	 * @param lineId
	 */
	public static void findWhereLineIdEquals(int lineId)
	{
		try {
			LogindetailsviewDao _dao = getLogindetailsviewDao();
			Logindetailsview _result[] = _dao.findWhereLineIdEquals(lineId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereUpdatedDateTimeEquals'
	 * 
	 * @param updatedDateTime
	 */
	public static void findWhereUpdatedDateTimeEquals(Date updatedDateTime)
	{
		try {
			LogindetailsviewDao _dao = getLogindetailsviewDao();
			Logindetailsview _result[] = _dao.findWhereUpdatedDateTimeEquals(updatedDateTime);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereStatusEquals'
	 * 
	 * @param status
	 */
	public static void findWhereStatusEquals(int status)
	{
		try {
			LogindetailsviewDao _dao = getLogindetailsviewDao();
			Logindetailsview _result[] = _dao.findWhereStatusEquals(status);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereStageidEquals'
	 * 
	 * @param stageid
	 */
	public static void findWhereStageidEquals(int stageid)
	{
		try {
			LogindetailsviewDao _dao = getLogindetailsviewDao();
			Logindetailsview _result[] = _dao.findWhereStageidEquals(stageid);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereProductFamilyIdEquals'
	 * 
	 * @param productFamilyId
	 */
	public static void findWhereProductFamilyIdEquals(int productFamilyId)
	{
		try {
			LogindetailsviewDao _dao = getLogindetailsviewDao();
			Logindetailsview _result[] = _dao.findWhereProductFamilyIdEquals(productFamilyId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereShiftEquals'
	 * 
	 * @param shift
	 */
	public static void findWhereShiftEquals(int shift)
	{
		try {
			LogindetailsviewDao _dao = getLogindetailsviewDao();
			Logindetailsview _result[] = _dao.findWhereShiftEquals(shift);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereIpaddressEquals'
	 * 
	 * @param ipaddress
	 */
	public static void findWhereIpaddressEquals(String ipaddress)
	{
		try {
			LogindetailsviewDao _dao = getLogindetailsviewDao();
			Logindetailsview _result[] = _dao.findWhereIpaddressEquals(ipaddress);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereLoginDateEquals'
	 * 
	 * @param loginDate
	 */
	public static void findWhereLoginDateEquals(Date loginDate)
	{
		try {
			LogindetailsviewDao _dao = getLogindetailsviewDao();
			Logindetailsview _result[] = _dao.findWhereLoginDateEquals(loginDate);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereLineNameEquals'
	 * 
	 * @param lineName
	 */
	public static void findWhereLineNameEquals(String lineName)
	{
		try {
			LogindetailsviewDao _dao = getLogindetailsviewDao();
			Logindetailsview _result[] = _dao.findWhereLineNameEquals(lineName);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereLineStatusEquals'
	 * 
	 * @param lineStatus
	 */
	public static void findWhereLineStatusEquals(int lineStatus)
	{
		try {
			LogindetailsviewDao _dao = getLogindetailsviewDao();
			Logindetailsview _result[] = _dao.findWhereLineStatusEquals(lineStatus);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereLineOrderNoEquals'
	 * 
	 * @param lineOrderNo
	 */
	public static void findWhereLineOrderNoEquals(int lineOrderNo)
	{
		try {
			LogindetailsviewDao _dao = getLogindetailsviewDao();
			Logindetailsview _result[] = _dao.findWhereLineOrderNoEquals(lineOrderNo);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereProductFamilyStatusEquals'
	 * 
	 * @param productFamilyStatus
	 */
	public static void findWhereProductFamilyStatusEquals(int productFamilyStatus)
	{
		try {
			LogindetailsviewDao _dao = getLogindetailsviewDao();
			Logindetailsview _result[] = _dao.findWhereProductFamilyStatusEquals(productFamilyStatus);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereGenderEquals'
	 * 
	 * @param gender
	 */
	public static void findWhereGenderEquals(String gender)
	{
		try {
			LogindetailsviewDao _dao = getLogindetailsviewDao();
			Logindetailsview _result[] = _dao.findWhereGenderEquals(gender);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereFunctionIdEquals'
	 * 
	 * @param functionId
	 */
	public static void findWhereFunctionIdEquals(int functionId)
	{
		try {
			LogindetailsviewDao _dao = getLogindetailsviewDao();
			Logindetailsview _result[] = _dao.findWhereFunctionIdEquals(functionId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereAttendanceDateEquals'
	 * 
	 * @param attendanceDate
	 */
	public static void findWhereAttendanceDateEquals(String attendanceDate)
	{
		try {
			LogindetailsviewDao _dao = getLogindetailsviewDao();
			Logindetailsview _result[] = _dao.findWhereAttendanceDateEquals(attendanceDate);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereTuningStationNoEquals'
	 * 
	 * @param tuningStationNo
	 */
	public static void findWhereTuningStationNoEquals(String tuningStationNo)
	{
		try {
			LogindetailsviewDao _dao = getLogindetailsviewDao();
			Logindetailsview _result[] = _dao.findWhereTuningStationNoEquals(tuningStationNo);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereRouteNameEquals'
	 * 
	 * @param routeName
	 */
	public static void findWhereRouteNameEquals(String routeName)
	{
		try {
			LogindetailsviewDao _dao = getLogindetailsviewDao();
			Logindetailsview _result[] = _dao.findWhereRouteNameEquals(routeName);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereFunctionNameEquals'
	 * 
	 * @param functionName
	 */
	public static void findWhereFunctionNameEquals(String functionName)
	{
		try {
			LogindetailsviewDao _dao = getLogindetailsviewDao();
			Logindetailsview _result[] = _dao.findWhereFunctionNameEquals(functionName);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereLogoutDateEquals'
	 * 
	 * @param logoutDate
	 */
	public static void findWhereLogoutDateEquals(Date logoutDate)
	{
		try {
			LogindetailsviewDao _dao = getLogindetailsviewDao();
			Logindetailsview _result[] = _dao.findWhereLogoutDateEquals(logoutDate);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereShiftDateEquals'
	 * 
	 * @param shiftDate
	 */
	public static void findWhereShiftDateEquals(Date shiftDate)
	{
		try {
			LogindetailsviewDao _dao = getLogindetailsviewDao();
			Logindetailsview _result[] = _dao.findWhereShiftDateEquals(shiftDate);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereTuningStatusEquals'
	 * 
	 * @param tuningStatus
	 */
	public static void findWhereTuningStatusEquals(int tuningStatus)
	{
		try {
			LogindetailsviewDao _dao = getLogindetailsviewDao();
			Logindetailsview _result[] = _dao.findWhereTuningStatusEquals(tuningStatus);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereTuningAverageTimeEquals'
	 * 
	 * @param tuningAverageTime
	 */
	public static void findWhereTuningAverageTimeEquals(double tuningAverageTime)
	{
		try {
			LogindetailsviewDao _dao = getLogindetailsviewDao();
			Logindetailsview _result[] = _dao.findWhereTuningAverageTimeEquals(tuningAverageTime);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereNoOfUnitsTunedEquals'
	 * 
	 * @param noOfUnitsTuned
	 */
	public static void findWhereNoOfUnitsTunedEquals(int noOfUnitsTuned)
	{
		try {
			LogindetailsviewDao _dao = getLogindetailsviewDao();
			Logindetailsview _result[] = _dao.findWhereNoOfUnitsTunedEquals(noOfUnitsTuned);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereBatchEquals'
	 * 
	 * @param batch
	 */
	public static void findWhereBatchEquals(int batch)
	{
		try {
			LogindetailsviewDao _dao = getLogindetailsviewDao();
			Logindetailsview _result[] = _dao.findWhereBatchEquals(batch);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereEmpStatusEquals'
	 * 
	 * @param empStatus
	 */
	public static void findWhereEmpStatusEquals(int empStatus)
	{
		try {
			LogindetailsviewDao _dao = getLogindetailsviewDao();
			Logindetailsview _result[] = _dao.findWhereEmpStatusEquals(empStatus);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereBatchNameEquals'
	 * 
	 * @param batchName
	 */
	public static void findWhereBatchNameEquals(String batchName)
	{
		try {
			LogindetailsviewDao _dao = getLogindetailsviewDao();
			Logindetailsview _result[] = _dao.findWhereBatchNameEquals(batchName);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereErtmemberEquals'
	 * 
	 * @param ertmember
	 */
	public static void findWhereErtmemberEquals(int ertmember)
	{
		try {
			LogindetailsviewDao _dao = getLogindetailsviewDao();
			Logindetailsview _result[] = _dao.findWhereErtmemberEquals(ertmember);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereNoOfCertiEquals'
	 * 
	 * @param noOfCerti
	 */
	public static void findWhereNoOfCertiEquals(int noOfCerti)
	{
		try {
			LogindetailsviewDao _dao = getLogindetailsviewDao();
			Logindetailsview _result[] = _dao.findWhereNoOfCertiEquals(noOfCerti);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getLogindetailsviewDao'
	 * 
	 * @return LogindetailsviewDao
	 */
	public static LogindetailsviewDao getLogindetailsviewDao()
	{
		return LogindetailsviewDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(Logindetailsview dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getEmpPhoto() );
		buf.append( ", " );
		buf.append( dto.getLoginId() );
		buf.append( ", " );
		buf.append( dto.getEmpCode() );
		buf.append( ", " );
		buf.append( dto.getEmpId() );
		buf.append( ", " );
		buf.append( dto.getEmpName() );
		buf.append( ", " );
		buf.append( dto.getCertifiedStatus() );
		buf.append( ", " );
		buf.append( dto.getStageName() );
		buf.append( ", " );
		buf.append( dto.getProductFamilyName() );
		buf.append( ", " );
		buf.append( dto.getLineId() );
		buf.append( ", " );
		buf.append( dto.getUpdatedDateTime() );
		buf.append( ", " );
		buf.append( dto.getStatus() );
		buf.append( ", " );
		buf.append( dto.getStageid() );
		buf.append( ", " );
		buf.append( dto.getProductFamilyId() );
		buf.append( ", " );
		buf.append( dto.getShift() );
		buf.append( ", " );
		buf.append( dto.getIpaddress() );
		buf.append( ", " );
		buf.append( dto.getLoginDate() );
		buf.append( ", " );
		buf.append( dto.getLineName() );
		buf.append( ", " );
		buf.append( dto.getLineStatus() );
		buf.append( ", " );
		buf.append( dto.getLineOrderNo() );
		buf.append( ", " );
		buf.append( dto.getProductFamilyStatus() );
		buf.append( ", " );
		buf.append( dto.getGender() );
		buf.append( ", " );
		buf.append( dto.getFunctionId() );
		buf.append( ", " );
		buf.append( dto.getAttendanceDate() );
		buf.append( ", " );
		buf.append( dto.getTuningStationNo() );
		buf.append( ", " );
		buf.append( dto.getRouteName() );
		buf.append( ", " );
		buf.append( dto.getFunctionName() );
		buf.append( ", " );
		buf.append( dto.getLogoutDate() );
		buf.append( ", " );
		buf.append( dto.getShiftDate() );
		buf.append( ", " );
		buf.append( dto.getTuningStatus() );
		buf.append( ", " );
		buf.append( dto.getTuningAverageTime() );
		buf.append( ", " );
		buf.append( dto.getNoOfUnitsTuned() );
		buf.append( ", " );
		buf.append( dto.getBatch() );
		buf.append( ", " );
		buf.append( dto.getEmpStatus() );
		buf.append( ", " );
		buf.append( dto.getBatchName() );
		buf.append( ", " );
		buf.append( dto.getErtmember() );
		buf.append( ", " );
		buf.append( dto.getNoOfCerti() );
		System.out.println( buf.toString() );
	}

}
