/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.rytways.nsn.db.dto;

import com.rytways.nsn.db.dao.*;
import com.rytways.nsn.db.factory.*;
import com.rytways.nsn.db.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class Logindetailsview implements Serializable
{
	/** 
	 * This attribute maps to the column EmpPhoto in the logindetailsview table.
	 */
	protected String empPhoto;

	/** 
	 * This attribute maps to the column LoginId in the logindetailsview table.
	 */
	protected int loginId;

	/** 
	 * This attribute maps to the column EmpCode in the logindetailsview table.
	 */
	protected int empCode;

	/** 
	 * This attribute represents whether the primitive attribute empCode is null.
	 */
	protected boolean empCodeNull = true;

	/** 
	 * This attribute maps to the column EmpId in the logindetailsview table.
	 */
	protected int empId;

	/** 
	 * This attribute represents whether the primitive attribute empId is null.
	 */
	protected boolean empIdNull = true;

	/** 
	 * This attribute maps to the column EmpName in the logindetailsview table.
	 */
	protected String empName;

	/** 
	 * This attribute maps to the column CertifiedStatus in the logindetailsview table.
	 */
	protected int certifiedStatus;

	/** 
	 * This attribute represents whether the primitive attribute certifiedStatus is null.
	 */
	protected boolean certifiedStatusNull = true;

	/** 
	 * This attribute maps to the column StageName in the logindetailsview table.
	 */
	protected String stageName;

	/** 
	 * This attribute maps to the column ProductFamilyName in the logindetailsview table.
	 */
	protected String productFamilyName;

	/** 
	 * This attribute maps to the column LineId in the logindetailsview table.
	 */
	protected int lineId;

	/** 
	 * This attribute represents whether the primitive attribute lineId is null.
	 */
	protected boolean lineIdNull = true;

	/** 
	 * This attribute maps to the column UpdatedDateTime in the logindetailsview table.
	 */
	protected Date updatedDateTime;

	/** 
	 * This attribute maps to the column Status in the logindetailsview table.
	 */
	protected int status;

	/** 
	 * This attribute represents whether the primitive attribute status is null.
	 */
	protected boolean statusNull = true;

	/** 
	 * This attribute maps to the column Stageid in the logindetailsview table.
	 */
	protected int stageid;

	/** 
	 * This attribute represents whether the primitive attribute stageid is null.
	 */
	protected boolean stageidNull = true;

	/** 
	 * This attribute maps to the column ProductFamilyId in the logindetailsview table.
	 */
	protected int productFamilyId;

	/** 
	 * This attribute represents whether the primitive attribute productFamilyId is null.
	 */
	protected boolean productFamilyIdNull = true;

	/** 
	 * This attribute maps to the column Shift in the logindetailsview table.
	 */
	protected int shift;

	/** 
	 * This attribute represents whether the primitive attribute shift is null.
	 */
	protected boolean shiftNull = true;

	/** 
	 * This attribute maps to the column IPAddress in the logindetailsview table.
	 */
	protected String ipaddress;

	/** 
	 * This attribute maps to the column LoginDate in the logindetailsview table.
	 */
	protected Date loginDate;

	/** 
	 * This attribute maps to the column LineName in the logindetailsview table.
	 */
	protected String lineName;

	/** 
	 * This attribute maps to the column LineStatus in the logindetailsview table.
	 */
	protected int lineStatus;

	/** 
	 * This attribute represents whether the primitive attribute lineStatus is null.
	 */
	protected boolean lineStatusNull = true;

	/** 
	 * This attribute maps to the column LineOrderNo in the logindetailsview table.
	 */
	protected int lineOrderNo;

	/** 
	 * This attribute represents whether the primitive attribute lineOrderNo is null.
	 */
	protected boolean lineOrderNoNull = true;

	/** 
	 * This attribute maps to the column ProductFamilyStatus in the logindetailsview table.
	 */
	protected int productFamilyStatus;

	/** 
	 * This attribute represents whether the primitive attribute productFamilyStatus is null.
	 */
	protected boolean productFamilyStatusNull = true;

	/** 
	 * This attribute maps to the column Gender in the logindetailsview table.
	 */
	protected String gender;

	/** 
	 * This attribute maps to the column FunctionId in the logindetailsview table.
	 */
	protected int functionId;

	/** 
	 * This attribute represents whether the primitive attribute functionId is null.
	 */
	protected boolean functionIdNull = true;

	/** 
	 * This attribute maps to the column AttendanceDate in the logindetailsview table.
	 */
	protected String attendanceDate;

	/** 
	 * This attribute maps to the column TuningStationNo in the logindetailsview table.
	 */
	protected String tuningStationNo;

	/** 
	 * This attribute maps to the column RouteName in the logindetailsview table.
	 */
	protected String routeName;

	/** 
	 * This attribute maps to the column FunctionName in the logindetailsview table.
	 */
	protected String functionName;

	/** 
	 * This attribute maps to the column LogoutDate in the logindetailsview table.
	 */
	protected Date logoutDate;

	/** 
	 * This attribute maps to the column ShiftDate in the logindetailsview table.
	 */
	protected Date shiftDate;

	/** 
	 * This attribute maps to the column TuningStatus in the logindetailsview table.
	 */
	protected int tuningStatus;

	/** 
	 * This attribute represents whether the primitive attribute tuningStatus is null.
	 */
	protected boolean tuningStatusNull = true;

	/** 
	 * This attribute maps to the column TuningAverageTime in the logindetailsview table.
	 */
	protected double tuningAverageTime;

	/** 
	 * This attribute represents whether the primitive attribute tuningAverageTime is null.
	 */
	protected boolean tuningAverageTimeNull = true;

	/** 
	 * This attribute maps to the column NoOfUnitsTuned in the logindetailsview table.
	 */
	protected int noOfUnitsTuned;

	/** 
	 * This attribute represents whether the primitive attribute noOfUnitsTuned is null.
	 */
	protected boolean noOfUnitsTunedNull = true;

	/** 
	 * This attribute maps to the column Batch in the logindetailsview table.
	 */
	protected int batch;

	/** 
	 * This attribute represents whether the primitive attribute batch is null.
	 */
	protected boolean batchNull = true;

	/** 
	 * This attribute maps to the column EmpStatus in the logindetailsview table.
	 */
	protected int empStatus;

	/** 
	 * This attribute represents whether the primitive attribute empStatus is null.
	 */
	protected boolean empStatusNull = true;

	/** 
	 * This attribute maps to the column BatchName in the logindetailsview table.
	 */
	protected String batchName;

	/** 
	 * This attribute maps to the column ERTMember in the logindetailsview table.
	 */
	protected int ertmember;

	/** 
	 * This attribute represents whether the primitive attribute ertmember is null.
	 */
	protected boolean ertmemberNull = true;

	/** 
	 * This attribute maps to the column NoOfCerti in the logindetailsview table.
	 */
	protected int noOfCerti;

	/** 
	 * This attribute represents whether the primitive attribute noOfCerti is null.
	 */
	protected boolean noOfCertiNull = true;

	/**
	 * Method 'Logindetailsview'
	 * 
	 */
	public Logindetailsview()
	{
	}

	/**
	 * Method 'getEmpPhoto'
	 * 
	 * @return String
	 */
	public String getEmpPhoto()
	{
		return empPhoto;
	}

	/**
	 * Method 'setEmpPhoto'
	 * 
	 * @param empPhoto
	 */
	public void setEmpPhoto(String empPhoto)
	{
		this.empPhoto = empPhoto;
	}

	/**
	 * Method 'getLoginId'
	 * 
	 * @return int
	 */
	public int getLoginId()
	{
		return loginId;
	}

	/**
	 * Method 'setLoginId'
	 * 
	 * @param loginId
	 */
	public void setLoginId(int loginId)
	{
		this.loginId = loginId;
	}

	/**
	 * Method 'getEmpCode'
	 * 
	 * @return int
	 */
	public int getEmpCode()
	{
		return empCode;
	}

	/**
	 * Method 'setEmpCode'
	 * 
	 * @param empCode
	 */
	public void setEmpCode(int empCode)
	{
		this.empCode = empCode;
		this.empCodeNull = false;
	}

	/**
	 * Method 'setEmpCodeNull'
	 * 
	 * @param value
	 */
	public void setEmpCodeNull(boolean value)
	{
		this.empCodeNull = value;
	}

	/**
	 * Method 'isEmpCodeNull'
	 * 
	 * @return boolean
	 */
	public boolean isEmpCodeNull()
	{
		return empCodeNull;
	}

	/**
	 * Method 'getEmpId'
	 * 
	 * @return int
	 */
	public int getEmpId()
	{
		return empId;
	}

	/**
	 * Method 'setEmpId'
	 * 
	 * @param empId
	 */
	public void setEmpId(int empId)
	{
		this.empId = empId;
		this.empIdNull = false;
	}

	/**
	 * Method 'setEmpIdNull'
	 * 
	 * @param value
	 */
	public void setEmpIdNull(boolean value)
	{
		this.empIdNull = value;
	}

	/**
	 * Method 'isEmpIdNull'
	 * 
	 * @return boolean
	 */
	public boolean isEmpIdNull()
	{
		return empIdNull;
	}

	/**
	 * Method 'getEmpName'
	 * 
	 * @return String
	 */
	public String getEmpName()
	{
		return empName;
	}

	/**
	 * Method 'setEmpName'
	 * 
	 * @param empName
	 */
	public void setEmpName(String empName)
	{
		this.empName = empName;
	}

	/**
	 * Method 'getCertifiedStatus'
	 * 
	 * @return int
	 */
	public int getCertifiedStatus()
	{
		return certifiedStatus;
	}

	/**
	 * Method 'setCertifiedStatus'
	 * 
	 * @param certifiedStatus
	 */
	public void setCertifiedStatus(int certifiedStatus)
	{
		this.certifiedStatus = certifiedStatus;
		this.certifiedStatusNull = false;
	}

	/**
	 * Method 'setCertifiedStatusNull'
	 * 
	 * @param value
	 */
	public void setCertifiedStatusNull(boolean value)
	{
		this.certifiedStatusNull = value;
	}

	/**
	 * Method 'isCertifiedStatusNull'
	 * 
	 * @return boolean
	 */
	public boolean isCertifiedStatusNull()
	{
		return certifiedStatusNull;
	}

	/**
	 * Method 'getStageName'
	 * 
	 * @return String
	 */
	public String getStageName()
	{
		return stageName;
	}

	/**
	 * Method 'setStageName'
	 * 
	 * @param stageName
	 */
	public void setStageName(String stageName)
	{
		this.stageName = stageName;
	}

	/**
	 * Method 'getProductFamilyName'
	 * 
	 * @return String
	 */
	public String getProductFamilyName()
	{
		return productFamilyName;
	}

	/**
	 * Method 'setProductFamilyName'
	 * 
	 * @param productFamilyName
	 */
	public void setProductFamilyName(String productFamilyName)
	{
		this.productFamilyName = productFamilyName;
	}

	/**
	 * Method 'getLineId'
	 * 
	 * @return int
	 */
	public int getLineId()
	{
		return lineId;
	}

	/**
	 * Method 'setLineId'
	 * 
	 * @param lineId
	 */
	public void setLineId(int lineId)
	{
		this.lineId = lineId;
		this.lineIdNull = false;
	}

	/**
	 * Method 'setLineIdNull'
	 * 
	 * @param value
	 */
	public void setLineIdNull(boolean value)
	{
		this.lineIdNull = value;
	}

	/**
	 * Method 'isLineIdNull'
	 * 
	 * @return boolean
	 */
	public boolean isLineIdNull()
	{
		return lineIdNull;
	}

	/**
	 * Method 'getUpdatedDateTime'
	 * 
	 * @return Date
	 */
	public Date getUpdatedDateTime()
	{
		return updatedDateTime;
	}

	/**
	 * Method 'setUpdatedDateTime'
	 * 
	 * @param updatedDateTime
	 */
	public void setUpdatedDateTime(Date updatedDateTime)
	{
		this.updatedDateTime = updatedDateTime;
	}

	/**
	 * Method 'getStatus'
	 * 
	 * @return int
	 */
	public int getStatus()
	{
		return status;
	}

	/**
	 * Method 'setStatus'
	 * 
	 * @param status
	 */
	public void setStatus(int status)
	{
		this.status = status;
		this.statusNull = false;
	}

	/**
	 * Method 'setStatusNull'
	 * 
	 * @param value
	 */
	public void setStatusNull(boolean value)
	{
		this.statusNull = value;
	}

	/**
	 * Method 'isStatusNull'
	 * 
	 * @return boolean
	 */
	public boolean isStatusNull()
	{
		return statusNull;
	}

	/**
	 * Method 'getStageid'
	 * 
	 * @return int
	 */
	public int getStageid()
	{
		return stageid;
	}

	/**
	 * Method 'setStageid'
	 * 
	 * @param stageid
	 */
	public void setStageid(int stageid)
	{
		this.stageid = stageid;
		this.stageidNull = false;
	}

	/**
	 * Method 'setStageidNull'
	 * 
	 * @param value
	 */
	public void setStageidNull(boolean value)
	{
		this.stageidNull = value;
	}

	/**
	 * Method 'isStageidNull'
	 * 
	 * @return boolean
	 */
	public boolean isStageidNull()
	{
		return stageidNull;
	}

	/**
	 * Method 'getProductFamilyId'
	 * 
	 * @return int
	 */
	public int getProductFamilyId()
	{
		return productFamilyId;
	}

	/**
	 * Method 'setProductFamilyId'
	 * 
	 * @param productFamilyId
	 */
	public void setProductFamilyId(int productFamilyId)
	{
		this.productFamilyId = productFamilyId;
		this.productFamilyIdNull = false;
	}

	/**
	 * Method 'setProductFamilyIdNull'
	 * 
	 * @param value
	 */
	public void setProductFamilyIdNull(boolean value)
	{
		this.productFamilyIdNull = value;
	}

	/**
	 * Method 'isProductFamilyIdNull'
	 * 
	 * @return boolean
	 */
	public boolean isProductFamilyIdNull()
	{
		return productFamilyIdNull;
	}

	/**
	 * Method 'getShift'
	 * 
	 * @return int
	 */
	public int getShift()
	{
		return shift;
	}

	/**
	 * Method 'setShift'
	 * 
	 * @param shift
	 */
	public void setShift(int shift)
	{
		this.shift = shift;
		this.shiftNull = false;
	}

	/**
	 * Method 'setShiftNull'
	 * 
	 * @param value
	 */
	public void setShiftNull(boolean value)
	{
		this.shiftNull = value;
	}

	/**
	 * Method 'isShiftNull'
	 * 
	 * @return boolean
	 */
	public boolean isShiftNull()
	{
		return shiftNull;
	}

	/**
	 * Method 'getIpaddress'
	 * 
	 * @return String
	 */
	public String getIpaddress()
	{
		return ipaddress;
	}

	/**
	 * Method 'setIpaddress'
	 * 
	 * @param ipaddress
	 */
	public void setIpaddress(String ipaddress)
	{
		this.ipaddress = ipaddress;
	}

	/**
	 * Method 'getLoginDate'
	 * 
	 * @return Date
	 */
	public Date getLoginDate()
	{
		return loginDate;
	}

	/**
	 * Method 'setLoginDate'
	 * 
	 * @param loginDate
	 */
	public void setLoginDate(Date loginDate)
	{
		this.loginDate = loginDate;
	}

	/**
	 * Method 'getLineName'
	 * 
	 * @return String
	 */
	public String getLineName()
	{
		return lineName;
	}

	/**
	 * Method 'setLineName'
	 * 
	 * @param lineName
	 */
	public void setLineName(String lineName)
	{
		this.lineName = lineName;
	}

	/**
	 * Method 'getLineStatus'
	 * 
	 * @return int
	 */
	public int getLineStatus()
	{
		return lineStatus;
	}

	/**
	 * Method 'setLineStatus'
	 * 
	 * @param lineStatus
	 */
	public void setLineStatus(int lineStatus)
	{
		this.lineStatus = lineStatus;
		this.lineStatusNull = false;
	}

	/**
	 * Method 'setLineStatusNull'
	 * 
	 * @param value
	 */
	public void setLineStatusNull(boolean value)
	{
		this.lineStatusNull = value;
	}

	/**
	 * Method 'isLineStatusNull'
	 * 
	 * @return boolean
	 */
	public boolean isLineStatusNull()
	{
		return lineStatusNull;
	}

	/**
	 * Method 'getLineOrderNo'
	 * 
	 * @return int
	 */
	public int getLineOrderNo()
	{
		return lineOrderNo;
	}

	/**
	 * Method 'setLineOrderNo'
	 * 
	 * @param lineOrderNo
	 */
	public void setLineOrderNo(int lineOrderNo)
	{
		this.lineOrderNo = lineOrderNo;
		this.lineOrderNoNull = false;
	}

	/**
	 * Method 'setLineOrderNoNull'
	 * 
	 * @param value
	 */
	public void setLineOrderNoNull(boolean value)
	{
		this.lineOrderNoNull = value;
	}

	/**
	 * Method 'isLineOrderNoNull'
	 * 
	 * @return boolean
	 */
	public boolean isLineOrderNoNull()
	{
		return lineOrderNoNull;
	}

	/**
	 * Method 'getProductFamilyStatus'
	 * 
	 * @return int
	 */
	public int getProductFamilyStatus()
	{
		return productFamilyStatus;
	}

	/**
	 * Method 'setProductFamilyStatus'
	 * 
	 * @param productFamilyStatus
	 */
	public void setProductFamilyStatus(int productFamilyStatus)
	{
		this.productFamilyStatus = productFamilyStatus;
		this.productFamilyStatusNull = false;
	}

	/**
	 * Method 'setProductFamilyStatusNull'
	 * 
	 * @param value
	 */
	public void setProductFamilyStatusNull(boolean value)
	{
		this.productFamilyStatusNull = value;
	}

	/**
	 * Method 'isProductFamilyStatusNull'
	 * 
	 * @return boolean
	 */
	public boolean isProductFamilyStatusNull()
	{
		return productFamilyStatusNull;
	}

	/**
	 * Method 'getGender'
	 * 
	 * @return String
	 */
	public String getGender()
	{
		return gender;
	}

	/**
	 * Method 'setGender'
	 * 
	 * @param gender
	 */
	public void setGender(String gender)
	{
		this.gender = gender;
	}

	/**
	 * Method 'getFunctionId'
	 * 
	 * @return int
	 */
	public int getFunctionId()
	{
		return functionId;
	}

	/**
	 * Method 'setFunctionId'
	 * 
	 * @param functionId
	 */
	public void setFunctionId(int functionId)
	{
		this.functionId = functionId;
		this.functionIdNull = false;
	}

	/**
	 * Method 'setFunctionIdNull'
	 * 
	 * @param value
	 */
	public void setFunctionIdNull(boolean value)
	{
		this.functionIdNull = value;
	}

	/**
	 * Method 'isFunctionIdNull'
	 * 
	 * @return boolean
	 */
	public boolean isFunctionIdNull()
	{
		return functionIdNull;
	}

	/**
	 * Method 'getAttendanceDate'
	 * 
	 * @return String
	 */
	public String getAttendanceDate()
	{
		return attendanceDate;
	}

	/**
	 * Method 'setAttendanceDate'
	 * 
	 * @param attendanceDate
	 */
	public void setAttendanceDate(String attendanceDate)
	{
		this.attendanceDate = attendanceDate;
	}

	/**
	 * Method 'getTuningStationNo'
	 * 
	 * @return String
	 */
	public String getTuningStationNo()
	{
		return tuningStationNo;
	}

	/**
	 * Method 'setTuningStationNo'
	 * 
	 * @param tuningStationNo
	 */
	public void setTuningStationNo(String tuningStationNo)
	{
		this.tuningStationNo = tuningStationNo;
	}

	/**
	 * Method 'getRouteName'
	 * 
	 * @return String
	 */
	public String getRouteName()
	{
		return routeName;
	}

	/**
	 * Method 'setRouteName'
	 * 
	 * @param routeName
	 */
	public void setRouteName(String routeName)
	{
		this.routeName = routeName;
	}

	/**
	 * Method 'getFunctionName'
	 * 
	 * @return String
	 */
	public String getFunctionName()
	{
		return functionName;
	}

	/**
	 * Method 'setFunctionName'
	 * 
	 * @param functionName
	 */
	public void setFunctionName(String functionName)
	{
		this.functionName = functionName;
	}

	/**
	 * Method 'getLogoutDate'
	 * 
	 * @return Date
	 */
	public Date getLogoutDate()
	{
		return logoutDate;
	}

	/**
	 * Method 'setLogoutDate'
	 * 
	 * @param logoutDate
	 */
	public void setLogoutDate(Date logoutDate)
	{
		this.logoutDate = logoutDate;
	}

	/**
	 * Method 'getShiftDate'
	 * 
	 * @return Date
	 */
	public Date getShiftDate()
	{
		return shiftDate;
	}

	/**
	 * Method 'setShiftDate'
	 * 
	 * @param shiftDate
	 */
	public void setShiftDate(Date shiftDate)
	{
		this.shiftDate = shiftDate;
	}

	/**
	 * Method 'getTuningStatus'
	 * 
	 * @return int
	 */
	public int getTuningStatus()
	{
		return tuningStatus;
	}

	/**
	 * Method 'setTuningStatus'
	 * 
	 * @param tuningStatus
	 */
	public void setTuningStatus(int tuningStatus)
	{
		this.tuningStatus = tuningStatus;
		this.tuningStatusNull = false;
	}

	/**
	 * Method 'setTuningStatusNull'
	 * 
	 * @param value
	 */
	public void setTuningStatusNull(boolean value)
	{
		this.tuningStatusNull = value;
	}

	/**
	 * Method 'isTuningStatusNull'
	 * 
	 * @return boolean
	 */
	public boolean isTuningStatusNull()
	{
		return tuningStatusNull;
	}

	/**
	 * Method 'getTuningAverageTime'
	 * 
	 * @return double
	 */
	public double getTuningAverageTime()
	{
		return tuningAverageTime;
	}

	/**
	 * Method 'setTuningAverageTime'
	 * 
	 * @param tuningAverageTime
	 */
	public void setTuningAverageTime(double tuningAverageTime)
	{
		this.tuningAverageTime = tuningAverageTime;
		this.tuningAverageTimeNull = false;
	}

	/**
	 * Method 'setTuningAverageTimeNull'
	 * 
	 * @param value
	 */
	public void setTuningAverageTimeNull(boolean value)
	{
		this.tuningAverageTimeNull = value;
	}

	/**
	 * Method 'isTuningAverageTimeNull'
	 * 
	 * @return boolean
	 */
	public boolean isTuningAverageTimeNull()
	{
		return tuningAverageTimeNull;
	}

	/**
	 * Method 'getNoOfUnitsTuned'
	 * 
	 * @return int
	 */
	public int getNoOfUnitsTuned()
	{
		return noOfUnitsTuned;
	}

	/**
	 * Method 'setNoOfUnitsTuned'
	 * 
	 * @param noOfUnitsTuned
	 */
	public void setNoOfUnitsTuned(int noOfUnitsTuned)
	{
		this.noOfUnitsTuned = noOfUnitsTuned;
		this.noOfUnitsTunedNull = false;
	}

	/**
	 * Method 'setNoOfUnitsTunedNull'
	 * 
	 * @param value
	 */
	public void setNoOfUnitsTunedNull(boolean value)
	{
		this.noOfUnitsTunedNull = value;
	}

	/**
	 * Method 'isNoOfUnitsTunedNull'
	 * 
	 * @return boolean
	 */
	public boolean isNoOfUnitsTunedNull()
	{
		return noOfUnitsTunedNull;
	}

	/**
	 * Method 'getBatch'
	 * 
	 * @return int
	 */
	public int getBatch()
	{
		return batch;
	}

	/**
	 * Method 'setBatch'
	 * 
	 * @param batch
	 */
	public void setBatch(int batch)
	{
		this.batch = batch;
		this.batchNull = false;
	}

	/**
	 * Method 'setBatchNull'
	 * 
	 * @param value
	 */
	public void setBatchNull(boolean value)
	{
		this.batchNull = value;
	}

	/**
	 * Method 'isBatchNull'
	 * 
	 * @return boolean
	 */
	public boolean isBatchNull()
	{
		return batchNull;
	}

	/**
	 * Method 'getEmpStatus'
	 * 
	 * @return int
	 */
	public int getEmpStatus()
	{
		return empStatus;
	}

	/**
	 * Method 'setEmpStatus'
	 * 
	 * @param empStatus
	 */
	public void setEmpStatus(int empStatus)
	{
		this.empStatus = empStatus;
		this.empStatusNull = false;
	}

	/**
	 * Method 'setEmpStatusNull'
	 * 
	 * @param value
	 */
	public void setEmpStatusNull(boolean value)
	{
		this.empStatusNull = value;
	}

	/**
	 * Method 'isEmpStatusNull'
	 * 
	 * @return boolean
	 */
	public boolean isEmpStatusNull()
	{
		return empStatusNull;
	}

	/**
	 * Method 'getBatchName'
	 * 
	 * @return String
	 */
	public String getBatchName()
	{
		return batchName;
	}

	/**
	 * Method 'setBatchName'
	 * 
	 * @param batchName
	 */
	public void setBatchName(String batchName)
	{
		this.batchName = batchName;
	}

	/**
	 * Method 'getErtmember'
	 * 
	 * @return int
	 */
	public int getErtmember()
	{
		return ertmember;
	}

	/**
	 * Method 'setErtmember'
	 * 
	 * @param ertmember
	 */
	public void setErtmember(int ertmember)
	{
		this.ertmember = ertmember;
		this.ertmemberNull = false;
	}

	/**
	 * Method 'setErtmemberNull'
	 * 
	 * @param value
	 */
	public void setErtmemberNull(boolean value)
	{
		this.ertmemberNull = value;
	}

	/**
	 * Method 'isErtmemberNull'
	 * 
	 * @return boolean
	 */
	public boolean isErtmemberNull()
	{
		return ertmemberNull;
	}

	/**
	 * Method 'getNoOfCerti'
	 * 
	 * @return int
	 */
	public int getNoOfCerti()
	{
		return noOfCerti;
	}

	/**
	 * Method 'setNoOfCerti'
	 * 
	 * @param noOfCerti
	 */
	public void setNoOfCerti(int noOfCerti)
	{
		this.noOfCerti = noOfCerti;
		this.noOfCertiNull = false;
	}

	/**
	 * Method 'setNoOfCertiNull'
	 * 
	 * @param value
	 */
	public void setNoOfCertiNull(boolean value)
	{
		this.noOfCertiNull = value;
	}

	/**
	 * Method 'isNoOfCertiNull'
	 * 
	 * @return boolean
	 */
	public boolean isNoOfCertiNull()
	{
		return noOfCertiNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Logindetailsview)) {
			return false;
		}
		
		final Logindetailsview _cast = (Logindetailsview) _other;
		if (empPhoto == null ? _cast.empPhoto != empPhoto : !empPhoto.equals( _cast.empPhoto )) {
			return false;
		}
		
		if (loginId != _cast.loginId) {
			return false;
		}
		
		if (empCode != _cast.empCode) {
			return false;
		}
		
		if (empCodeNull != _cast.empCodeNull) {
			return false;
		}
		
		if (empId != _cast.empId) {
			return false;
		}
		
		if (empIdNull != _cast.empIdNull) {
			return false;
		}
		
		if (empName == null ? _cast.empName != empName : !empName.equals( _cast.empName )) {
			return false;
		}
		
		if (certifiedStatus != _cast.certifiedStatus) {
			return false;
		}
		
		if (certifiedStatusNull != _cast.certifiedStatusNull) {
			return false;
		}
		
		if (stageName == null ? _cast.stageName != stageName : !stageName.equals( _cast.stageName )) {
			return false;
		}
		
		if (productFamilyName == null ? _cast.productFamilyName != productFamilyName : !productFamilyName.equals( _cast.productFamilyName )) {
			return false;
		}
		
		if (lineId != _cast.lineId) {
			return false;
		}
		
		if (lineIdNull != _cast.lineIdNull) {
			return false;
		}
		
		if (updatedDateTime == null ? _cast.updatedDateTime != updatedDateTime : !updatedDateTime.equals( _cast.updatedDateTime )) {
			return false;
		}
		
		if (status != _cast.status) {
			return false;
		}
		
		if (statusNull != _cast.statusNull) {
			return false;
		}
		
		if (stageid != _cast.stageid) {
			return false;
		}
		
		if (stageidNull != _cast.stageidNull) {
			return false;
		}
		
		if (productFamilyId != _cast.productFamilyId) {
			return false;
		}
		
		if (productFamilyIdNull != _cast.productFamilyIdNull) {
			return false;
		}
		
		if (shift != _cast.shift) {
			return false;
		}
		
		if (shiftNull != _cast.shiftNull) {
			return false;
		}
		
		if (ipaddress == null ? _cast.ipaddress != ipaddress : !ipaddress.equals( _cast.ipaddress )) {
			return false;
		}
		
		if (loginDate == null ? _cast.loginDate != loginDate : !loginDate.equals( _cast.loginDate )) {
			return false;
		}
		
		if (lineName == null ? _cast.lineName != lineName : !lineName.equals( _cast.lineName )) {
			return false;
		}
		
		if (lineStatus != _cast.lineStatus) {
			return false;
		}
		
		if (lineStatusNull != _cast.lineStatusNull) {
			return false;
		}
		
		if (lineOrderNo != _cast.lineOrderNo) {
			return false;
		}
		
		if (lineOrderNoNull != _cast.lineOrderNoNull) {
			return false;
		}
		
		if (productFamilyStatus != _cast.productFamilyStatus) {
			return false;
		}
		
		if (productFamilyStatusNull != _cast.productFamilyStatusNull) {
			return false;
		}
		
		if (gender == null ? _cast.gender != gender : !gender.equals( _cast.gender )) {
			return false;
		}
		
		if (functionId != _cast.functionId) {
			return false;
		}
		
		if (functionIdNull != _cast.functionIdNull) {
			return false;
		}
		
		if (attendanceDate == null ? _cast.attendanceDate != attendanceDate : !attendanceDate.equals( _cast.attendanceDate )) {
			return false;
		}
		
		if (tuningStationNo == null ? _cast.tuningStationNo != tuningStationNo : !tuningStationNo.equals( _cast.tuningStationNo )) {
			return false;
		}
		
		if (routeName == null ? _cast.routeName != routeName : !routeName.equals( _cast.routeName )) {
			return false;
		}
		
		if (functionName == null ? _cast.functionName != functionName : !functionName.equals( _cast.functionName )) {
			return false;
		}
		
		if (logoutDate == null ? _cast.logoutDate != logoutDate : !logoutDate.equals( _cast.logoutDate )) {
			return false;
		}
		
		if (shiftDate == null ? _cast.shiftDate != shiftDate : !shiftDate.equals( _cast.shiftDate )) {
			return false;
		}
		
		if (tuningStatus != _cast.tuningStatus) {
			return false;
		}
		
		if (tuningStatusNull != _cast.tuningStatusNull) {
			return false;
		}
		
		if (tuningAverageTime != _cast.tuningAverageTime) {
			return false;
		}
		
		if (tuningAverageTimeNull != _cast.tuningAverageTimeNull) {
			return false;
		}
		
		if (noOfUnitsTuned != _cast.noOfUnitsTuned) {
			return false;
		}
		
		if (noOfUnitsTunedNull != _cast.noOfUnitsTunedNull) {
			return false;
		}
		
		if (batch != _cast.batch) {
			return false;
		}
		
		if (batchNull != _cast.batchNull) {
			return false;
		}
		
		if (empStatus != _cast.empStatus) {
			return false;
		}
		
		if (empStatusNull != _cast.empStatusNull) {
			return false;
		}
		
		if (batchName == null ? _cast.batchName != batchName : !batchName.equals( _cast.batchName )) {
			return false;
		}
		
		if (ertmember != _cast.ertmember) {
			return false;
		}
		
		if (ertmemberNull != _cast.ertmemberNull) {
			return false;
		}
		
		if (noOfCerti != _cast.noOfCerti) {
			return false;
		}
		
		if (noOfCertiNull != _cast.noOfCertiNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (empPhoto != null) {
			_hashCode = 29 * _hashCode + empPhoto.hashCode();
		}
		
		_hashCode = 29 * _hashCode + loginId;
		_hashCode = 29 * _hashCode + empCode;
		_hashCode = 29 * _hashCode + (empCodeNull ? 1 : 0);
		_hashCode = 29 * _hashCode + empId;
		_hashCode = 29 * _hashCode + (empIdNull ? 1 : 0);
		if (empName != null) {
			_hashCode = 29 * _hashCode + empName.hashCode();
		}
		
		_hashCode = 29 * _hashCode + certifiedStatus;
		_hashCode = 29 * _hashCode + (certifiedStatusNull ? 1 : 0);
		if (stageName != null) {
			_hashCode = 29 * _hashCode + stageName.hashCode();
		}
		
		if (productFamilyName != null) {
			_hashCode = 29 * _hashCode + productFamilyName.hashCode();
		}
		
		_hashCode = 29 * _hashCode + lineId;
		_hashCode = 29 * _hashCode + (lineIdNull ? 1 : 0);
		if (updatedDateTime != null) {
			_hashCode = 29 * _hashCode + updatedDateTime.hashCode();
		}
		
		_hashCode = 29 * _hashCode + status;
		_hashCode = 29 * _hashCode + (statusNull ? 1 : 0);
		_hashCode = 29 * _hashCode + stageid;
		_hashCode = 29 * _hashCode + (stageidNull ? 1 : 0);
		_hashCode = 29 * _hashCode + productFamilyId;
		_hashCode = 29 * _hashCode + (productFamilyIdNull ? 1 : 0);
		_hashCode = 29 * _hashCode + shift;
		_hashCode = 29 * _hashCode + (shiftNull ? 1 : 0);
		if (ipaddress != null) {
			_hashCode = 29 * _hashCode + ipaddress.hashCode();
		}
		
		if (loginDate != null) {
			_hashCode = 29 * _hashCode + loginDate.hashCode();
		}
		
		if (lineName != null) {
			_hashCode = 29 * _hashCode + lineName.hashCode();
		}
		
		_hashCode = 29 * _hashCode + lineStatus;
		_hashCode = 29 * _hashCode + (lineStatusNull ? 1 : 0);
		_hashCode = 29 * _hashCode + lineOrderNo;
		_hashCode = 29 * _hashCode + (lineOrderNoNull ? 1 : 0);
		_hashCode = 29 * _hashCode + productFamilyStatus;
		_hashCode = 29 * _hashCode + (productFamilyStatusNull ? 1 : 0);
		if (gender != null) {
			_hashCode = 29 * _hashCode + gender.hashCode();
		}
		
		_hashCode = 29 * _hashCode + functionId;
		_hashCode = 29 * _hashCode + (functionIdNull ? 1 : 0);
		if (attendanceDate != null) {
			_hashCode = 29 * _hashCode + attendanceDate.hashCode();
		}
		
		if (tuningStationNo != null) {
			_hashCode = 29 * _hashCode + tuningStationNo.hashCode();
		}
		
		if (routeName != null) {
			_hashCode = 29 * _hashCode + routeName.hashCode();
		}
		
		if (functionName != null) {
			_hashCode = 29 * _hashCode + functionName.hashCode();
		}
		
		if (logoutDate != null) {
			_hashCode = 29 * _hashCode + logoutDate.hashCode();
		}
		
		if (shiftDate != null) {
			_hashCode = 29 * _hashCode + shiftDate.hashCode();
		}
		
		_hashCode = 29 * _hashCode + tuningStatus;
		_hashCode = 29 * _hashCode + (tuningStatusNull ? 1 : 0);
		long temp_tuningAverageTime = Double.doubleToLongBits(tuningAverageTime);
		_hashCode = 29 * _hashCode + (int) (temp_tuningAverageTime ^ (temp_tuningAverageTime >>> 32));
		_hashCode = 29 * _hashCode + (tuningAverageTimeNull ? 1 : 0);
		_hashCode = 29 * _hashCode + noOfUnitsTuned;
		_hashCode = 29 * _hashCode + (noOfUnitsTunedNull ? 1 : 0);
		_hashCode = 29 * _hashCode + batch;
		_hashCode = 29 * _hashCode + (batchNull ? 1 : 0);
		_hashCode = 29 * _hashCode + empStatus;
		_hashCode = 29 * _hashCode + (empStatusNull ? 1 : 0);
		if (batchName != null) {
			_hashCode = 29 * _hashCode + batchName.hashCode();
		}
		
		_hashCode = 29 * _hashCode + ertmember;
		_hashCode = 29 * _hashCode + (ertmemberNull ? 1 : 0);
		_hashCode = 29 * _hashCode + noOfCerti;
		_hashCode = 29 * _hashCode + (noOfCertiNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.rytways.nsn.db.dto.Logindetailsview: " );
		ret.append( "empPhoto=" + empPhoto );
		ret.append( ", loginId=" + loginId );
		ret.append( ", empCode=" + empCode );
		ret.append( ", empId=" + empId );
		ret.append( ", empName=" + empName );
		ret.append( ", certifiedStatus=" + certifiedStatus );
		ret.append( ", stageName=" + stageName );
		ret.append( ", productFamilyName=" + productFamilyName );
		ret.append( ", lineId=" + lineId );
		ret.append( ", updatedDateTime=" + updatedDateTime );
		ret.append( ", status=" + status );
		ret.append( ", stageid=" + stageid );
		ret.append( ", productFamilyId=" + productFamilyId );
		ret.append( ", shift=" + shift );
		ret.append( ", ipaddress=" + ipaddress );
		ret.append( ", loginDate=" + loginDate );
		ret.append( ", lineName=" + lineName );
		ret.append( ", lineStatus=" + lineStatus );
		ret.append( ", lineOrderNo=" + lineOrderNo );
		ret.append( ", productFamilyStatus=" + productFamilyStatus );
		ret.append( ", gender=" + gender );
		ret.append( ", functionId=" + functionId );
		ret.append( ", attendanceDate=" + attendanceDate );
		ret.append( ", tuningStationNo=" + tuningStationNo );
		ret.append( ", routeName=" + routeName );
		ret.append( ", functionName=" + functionName );
		ret.append( ", logoutDate=" + logoutDate );
		ret.append( ", shiftDate=" + shiftDate );
		ret.append( ", tuningStatus=" + tuningStatus );
		ret.append( ", tuningAverageTime=" + tuningAverageTime );
		ret.append( ", noOfUnitsTuned=" + noOfUnitsTuned );
		ret.append( ", batch=" + batch );
		ret.append( ", empStatus=" + empStatus );
		ret.append( ", batchName=" + batchName );
		ret.append( ", ertmember=" + ertmember );
		ret.append( ", noOfCerti=" + noOfCerti );
		return ret.toString();
	}

}
